title: Patrick Fuller
thumbnail: gauss-bare-kernel.png
description: Random thoughts on science, software development, and tech entrepreneurship.
url: http://www.patrickemmettfuller.com
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
